### ISSUE TITLE
More Keywords Support

### ISSUE THREAD

**Issue by JerryLife** [izhangzhihao/intellij-rainbow-fart#10]
I understand the voice package is limited. But it would be great if some common keywords or functions like ```while```, ```assert```, ```raise/throw```, ```print```, ```return``` can be supported.

**Comment by byxlle** [comment]
`def`  函数
`class`  类 , 对象

**Comment by izhangzhihao** [comment]
They ARE supported(if third-party voice packages have those in the `manifest.json` or `contributes.json`), so you are actually looking for third-party voice packages. Please goes to: https://github.com/topics/rainbow-fart
