### ISSUE TITLE
请问这个报错怎么弄

### ISSUE THREAD

**Issue by LauWingHung** [izhangzhihao/intellij-rainbow-fart#11]
![图片](https://user-images.githubusercontent.com/37165517/85280823-7a2ee880-b4bb-11ea-9908-8154a6c6e6df.png)

**Comment by LauWingHung** [comment]
我用idea,goland安装都是报这个错

**Comment by izhangzhihao** [comment]
不要解压zip

**Comment by LauWingHung** [comment]
好的谢谢

**Comment by LauWingHung** [comment]
那个触发关键字能不能改呢,比如function 输入func就有声音

**Comment by izhangzhihao** [comment]
> 那个触发关键字能不能改呢,比如function 输入func就有声音

可以啊，把语音包的关键字直接改成`func`就好了
