### ISSUE TITLE
Play voice only in active editor instance

### ISSUE THREAD

**Issue by chfanghr** [izhangzhihao/intellij-rainbow-fart#18]
The issue is that if you have multiple editor instance opened, the same voice may be played for many times. The simplest way to reproduce this bug on may machine is to open lots of projects in clion, close all editor instances using `Quit` entry in clion menu in dock, and open clion from jet brains toolbox. You'll hear the same voice being played on the same time.

**Comment by izhangzhihao** [comment]
Great catch!

**Comment by izhangzhihao** [comment]
Please confirm this snapshot build works for you. 
[intellij-rainbow-fart-1.2.zip](https://github.com/izhangzhihao/intellij-rainbow-fart/files/4818827/intellij-rainbow-fart-1.2.zip)

**Comment by chfanghr** [comment]
Problem sloved. Thanks for your work.
