### ISSUE TITLE
Webstorm 上能不能使用

### ISSUE THREAD

**Issue by Kay622** [izhangzhihao/intellij-rainbow-fart#20]
Webstorm 上没有语音提示，只能在idea 使用吗？

**Comment by izhangzhihao** [comment]
不是，支持JetBrains全系IDE

**Comment by Kay622** [comment]
但是我写代码的时候一点语音提示都没有，只在重启ide后，有一句问候，&nbsp;不知道为什么。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张志豪"<notifications@github.com&gt;; 
发送时间: 2020年6月24日(星期三) 下午2:57
收件人: "izhangzhihao/intellij-rainbow-fart"<intellij-rainbow-fart@noreply.github.com&gt;; 
抄送: "暗恋桃花源"<1522025433@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [izhangzhihao/intellij-rainbow-fart] Webstorm 上能不能使用 (#20)





 
不是，支持JetBrains全系IDE

**Comment by izhangzhihao** [comment]
输入function试试

**Comment by Kay622** [comment]
谢谢，全部敲出是有语音的，我之前是有提示了，直接回车输入了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张志豪"<notifications@github.com&gt;; 
发送时间: 2020年6月24日(星期三) 下午3:02
收件人: "izhangzhihao/intellij-rainbow-fart"<intellij-rainbow-fart@noreply.github.com&gt;; 
抄送: "暗恋桃花源"<1522025433@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [izhangzhihao/intellij-rainbow-fart] Webstorm 上能不能使用 (#20)





 
输入function试试
