### ISSUE TITLE
只支持2020大版本的Idea吗？

### ISSUE THREAD

**Issue by qingshui3000** [izhangzhihao/intellij-rainbow-fart#24]

**Comment by izhangzhihao** [comment]
https://github.com/izhangzhihao/intellij-rainbow-fart/issues/22#issuecomment-650693164

**Comment by izhangzhihao** [comment]
https://plugins.jetbrains.com/plugin/14543-rainbow-fart/versions

The new version already supports IntelliJ 2019.1 and above.
