### ISSUE TITLE
 hope can add custom settings keyword settings

### ISSUE THREAD

**Issue by kouzhihao** [izhangzhihao/intellij-rainbow-fart#28]

**Comment by izhangzhihao** [comment]
for example?

**Comment by kouzhihao** [comment]
I noticed,Keywords that trigger speech,Can only be fixed,Why not customize? for example :Can be set "public"  trigger original "function "  voice

**Comment by izhangzhihao** [comment]
Yes! at this moment, you can configure your own voice package(with your own keywords) or edit an existing voice package.

**Comment by izhangzhihao** [comment]
by the way, `public` is not always a function, eg,

```java
public static int ABC = 1
```

**Comment by izhangzhihao** [comment]
But, I will try to add true language support(eg, using AST to trigger voice, not keyword.)

**Comment by izhangzhihao** [comment]
duplicated with #27 .
