### ISSUE TITLE
Better support for cpp

### ISSUE THREAD

**Issue by chfanghr** [izhangzhihao/intellij-rainbow-fart#3]
Currently lots of keywords like `template` , `constexpr` and so on are not yet supported

**Comment by izhangzhihao** [comment]
Right, if we could get more voice resources relative to those keywords.

**Comment by izhangzhihao** [comment]
BTW, it would be great if someone can think about the keywords list and possible rainbow fart sentences. (Since I don't know much about cpp etc.)

**Comment by chfanghr** [comment]
I would like to participate in this after my final exam. To be honest, It's

**Comment by izhangzhihao** [comment]
Some third-party voice packages already have CPP supported, like: https://github.com/Nanguage/Rainbow-Fart-MBG
If you are looking for more third-party voice packages, please goes to: https://github.com/topics/rainbow-fart
