### ISSUE TITLE
This plugin takes too much CPU

### ISSUE THREAD

**Issue by mooczhou** [izhangzhihao/intellij-rainbow-fart#31]
This plugin takes up too much CPU and almost reached 20%,And I said that the mode is switched to sleep mode, or it will still use the CPU. Will the author have any optimization ideas for this?

**Comment by izhangzhihao** [comment]
I'm looking into this issue.

**Comment by izhangzhihao** [comment]
What is your env?

**Comment by izhangzhihao** [comment]
[intellij-rainbow-fart-1.2.3.zip](https://github.com/izhangzhihao/intellij-rainbow-fart/files/4862819/intellij-rainbow-fart-1.2.3.zip)

try this build snapshot.

**Comment by mooczhou** [comment]
goland in windows

**Comment by izhangzhihao** [comment]
> goland in windows

what do you mean?
