### ISSUE TITLE
Play Voice Base On Token Analysis

### ISSUE THREAD

**Issue by chfanghr** [izhangzhihao/intellij-rainbow-fart#35]
Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-fart/issues) before creating one.

## Please check

- [x] I already star this project.
- [x] If you are submitting a feature request, please do consider donating us on [AliPay/WeChatPay](https://github.com/izhangzhihao/intellij-rainbow-fart#support-me).
- [x] This issue/feature request is not reported before.

## Your programming language(s)

C++/Golang

## Current Behavior
Condider this code snippet:
```c++
KERFUFFLE_INLINE float UniformReal(const uint32_t val){
```
When Typing `UniformReal`, voice associated to `for` keyword will be played, which is obvious incorrect.

## Expected Behivior

Do not play any voice.

## Possible Solution
 In my opinion, this can be sloved by applying token analysis.

## Code snippet for reproduce (for bugs)
```c++
KERFUFFLE_INLINE float UniformReal(const uint32_t val){
```
And any other indentidiers which have keyword as their substring.

*NOTE: If you are going to report a bug but WITHOUT your env information, your issue will be closed directly.*

## Your Environment

- [x] my IDE version is Clion 2020.1.2.
* Plugin version: 1.2.4
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue will be closed directly.

```
CLion 2020.1.2
Build #CL-201.7846.88, built on June 3, 2020
Licensed to *****
Subscription is active until October 12, 2020
For educational use only.
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 2987M
Cores: 6
Registry: run.processes.with.pty=TRUE, ide.tree.collapse.recursively=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: zielu.gittoolbox, GrepConsole, Lua, Shifter, String Manipulation, com.intellij.clion-swift, com.appcodeplugins.swiftlint, com.chrisrm.idea.MaterialThemeUI, com.compilerexplorer.compilerexplorer, com.intellij.plugins.macoskeymap, com.jetbrains.plugins.ini4idea, intellij.clion.embedded.platformio, com.jfrog.conan.clion, com.mallowigi, com.vladsch.clionarduinoplugin, com.zero9178, mobi.hsz.idea.gitignore, in.xiv.cs, izhangzhihao.rainbow.fart, name.kropp.intellij.makefile, BashSupport, tanvd.grazi, Dart, izhangzhihao.rainbow.brackets, org.toml.lang, org.rust.lang, ru.phism.intellij.unreal, some.awesome
```

**Comment by izhangzhihao** [comment]
Duplicated with #27
