### ISSUE TITLE
设置了语音包的绝对路径，但没有起效

### ISSUE THREAD

**Issue by Mr-metasequoia** [izhangzhihao/intellij-rainbow-fart#64]
##  Environment

- √ my IDE version is 2020.1 or above/Android Studio 4.2 or above.
* Plugin version:1.3.5

IntelliJ IDEA 2021.1.2 (Ultimate Edition)
Build #IU-211.7442.40, built on June 1, 2021
Licensed to IntelliJ IDEA Evaluator
Expiration date: November 29, 2021
Runtime version: 11.0.11+9-b1341.57 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1900M
Cores: 12
Non-Bundled Plugins: io.zhile.research.ide-eval-resetter (2.1.14), izhangzhihao.rainbow.fart (1.3.5), com.alibaba.p3c.smartfox (2.1.1), org.jetbrains.kotlin (211-1.5.31-release-551-IJ7442.40), cn.yiiguxing.plugin.translate (3.1.1)
Kotlin: 211-1.5.31-release-551-IJ7442.40

![image](https://user-images.githubusercontent.com/76619254/139518908-1860cf82-43f1-4f59-820d-9ae16fca7d55.png)
![image](https://user-images.githubusercontent.com/76619254/139518870-4ed0d02f-88d9-45cd-b162-f22eff1bf26e.png)

我设置了语音包的绝对路径，但钉宫没有来骂我（悲
（不设置的话，内置小姐姐还是起效的！）
求救！otz

**Comment by izhangzhihao** [comment]
可能要重启？
