### ISSUE TITLE
发现没声音呢

### ISSUE THREAD

**Issue by fanmingyi** [izhangzhihao/intellij-rainbow-fart#9]
只有打开一个新工程时才会语音一次

**Comment by izhangzhihao** [comment]
???

**Comment by fanmingyi** [comment]
键入关键字无语音 2020.2EAP版本 @izhangzhihao

**Comment by fanmingyi** [comment]
另外我对这个工程非常喜欢,能否以后指导我IDEA的插件开发?

**Comment by izhangzhihao** [comment]
> 键入关键字无语音 2020.2EAP版本 @izhangzhihao

暂时需要输入完整关键词才能触发

**Comment by izhangzhihao** [comment]
通过智能提示选择的结果暂时不支持触发

**Comment by izhangzhihao** [comment]
如果你有时间的话，可以尝试一下给这个插件增加低版本IDE的支持，比如支持2018.3以上版本。
